import dns from 'dns';
import { resolve } from 'path';

import { sentryVitePlugin } from '@sentry/vite-plugin';
import react from '@vitejs/plugin-react';
import { visualizer } from 'rollup-plugin-visualizer';
import { defineConfig, loadEnv } from 'vite';

import mkcert from 'vite-plugin-mkcert';

dns.setDefaultResultOrder('ipv4first');

const VISUALIZER = false; // enable to generate bundle visualization on build
const DEFAULT_WAREHOUSE_SERVER = 'https://hmis-warehouse.dev.test';

// https://github.com/vitejs/vite/issues/2433#issuecomment-1487472995
function sourcemapExclude(opts) {
  return {
    name: 'sourcemap-exclude',
    transform(code, id) {
      if (opts?.excludeNodeModules && id.includes('node_modules')) {
        return {
          code,
          map: { mappings: '' },
        };
      }
    },
  };
}

export default defineConfig(({ command, mode }) => {
  const env = loadEnv(mode, process.cwd(), '');

  const hmisHost = env.HMIS_HOST || 'hmis.dev.test';
  // If HMIS_HOSTNAME is set, it may be a single value *or* a comma-separated list
  // of all HMIS hostnames accepted by the backend, in a multi-HMIS local setup.
  // Include all accepted HMIS hostnames in the dev cert generated by mkcert.
  const hmisHostnames = env.HMIS_HOSTNAME
    ? env.HMIS_HOSTNAME.split(',').map((h) => h.trim())
    : [hmisHost];

  // warehouseProxyServer is used below only in dev (command !== 'build')
  const warehouseProxyServer = {
    target: env.HMIS_SERVER_URL || DEFAULT_WAREHOUSE_SERVER,
    changeOrigin: true, // sets Host header
    headers: {
      Origin: env.HMIS_SERVER_URL || DEFAULT_WAREHOUSE_SERVER,
      // Pass the HMIS hostname so the warehouse can resolve the correct data source.
      // Use a custom header X-HMIS-Host because a reverse proxy (e.g. Traefik)
      // in front of Rails may overwrite X-Forwarded-Host.
      'X-HMIS-Host': hmisHost,
    },
    secure: false,
  };

  return {
    envPrefix: 'PUBLIC_',
    resolve: {
      alias: {
        '@': resolve(__dirname, './src'),
      },
    },
    plugins: [
      react(),
      mkcert({ hosts: hmisHostnames }),
      sourcemapExclude({ excludeNodeModules: true }),
      // Note: even though sourcemaps are public, we upload them to get additional Sentry tooling around releases
      ...(env.SENTRY_ORG && env.SENTRY_PROJECT && env.SENTRY_AUTH_TOKEN
        ? [
            sentryVitePlugin({
              org: env.SENTRY_ORG,
              project: env.SENTRY_PROJECT,
              authToken: env.SENTRY_AUTH_TOKEN,
              release: {
                uploadLegacySourcemaps: {
                  paths: ['dist/assets/'],
                  urlPrefix: '~/assets/',
                },
                name: env.PUBLIC_GIT_COMMIT_HASH,
                setCommits: {
                  repo: 'greenriver/hmis-frontend',
                  commit: env.FULL_GITHASH,
                },
              },
              // reactComponentAnnotation: { enabled: true, },
              telemetry: false,
              debug: false,
            }),
          ]
        : []),
    ],
    define: {
      __APP_ENV__: env.APP_ENV,
    },
    esbuild: {
      // https://github.com/vitejs/vite/issues/8644#issuecomment-1159308803
      logOverride: { 'this-is-undefined-in-esm': 'silent' },
      // Drop log statements when minifying
      pure: ['console.log', 'console.info', 'console.debug'],
    },
    test: {
      watch: false,
    },
    build: {
      rollupOptions: {
        plugins: [
          VISUALIZER && visualizer({ filename: 'bundle_analysis.html' }),
        ],
        output: {
          manualChunks(id) {
            if (id.includes('node_modules')) {
              return 'vendor';
            }
          },
        },
        onwarn(warning, defaultHandler) {
          if (warning.code === 'SOURCEMAP_ERROR') {
            return;
          }
          if (warning.code === 'MODULE_LEVEL_DIRECTIVE') {
            return;
          }
          defaultHandler(warning);
        },
      },
      commonjsOptions: { transformMixedEsModules: true },
      sourcemap: true,
      minify: mode === 'development' ? false : 'esbuild',
    },
    ...(command !== 'build' && {
      preview: {
        open: false,
        port: 5173, // expected in capybara system test instructions
        strictPort: true,
      },
      server: {
        port: 5173,
        open: true,
        host: hmisHost,
        https:
          env.SERVER_HTTPS === undefined ? true : env.SERVER_HTTPS === 'true',
        proxy: {
          '/hmis': warehouseProxyServer,
          '/dev-assets/theme': warehouseProxyServer,
          '/logo': warehouseProxyServer,
        },
      },
    }),
  };
});
