export const AlphaIncomeSources = [
  'A',
  'B',
  'C',
  'D',
  'E',
  'F',
  'G',
  'H',
  'I',
  'J',
  'K',
  'L',
  'M',
  'N',
];

export const EmptyIncomeSources = {
  'IncomeBenefit.incomeFromAnySource': 'DATA_NOT_COLLECTED',
  'IncomeBenefit.earned': null,
  'IncomeBenefit.earnedAmount': null,
  'IncomeBenefit.unemployment': null,
  'IncomeBenefit.unemploymentAmount': null,
  'IncomeBenefit.ssi': null,
  'IncomeBenefit.ssiAmount': null,
  'IncomeBenefit.ssdi': null,
  'IncomeBenefit.ssdiAmount': null,
  'IncomeBenefit.vaDisabilityService': null,
  'IncomeBenefit.vaDisabilityServiceAmount': null,
  'IncomeBenefit.vaDisabilityNonService': null,
  'IncomeBenefit.vaDisabilityNonServiceAmount': null,
  'IncomeBenefit.privateDisability': null,
  'IncomeBenefit.privateDisabilityAmount': null,
  'IncomeBenefit.workersComp': null,
  'IncomeBenefit.workersCompAmount': null,
  'IncomeBenefit.tanf': null,
  'IncomeBenefit.tanfAmount': null,
  'IncomeBenefit.ga': null,
  'IncomeBenefit.gaAmount': null,
  'IncomeBenefit.socSecRetirement': null,
  'IncomeBenefit.socSecRetirementAmount': null,
  'IncomeBenefit.pension': null,
  'IncomeBenefit.pensionAmount': null,
  'IncomeBenefit.childSupport': null,
  'IncomeBenefit.childSupportAmount': null,
  'IncomeBenefit.alimony': null,
  'IncomeBenefit.alimonyAmount': null,
  'IncomeBenefit.otherIncomeSource': null,
  'IncomeBenefit.otherIncomeAmount': null,
};

export const EmptyNonCashBenefits = {
  'IncomeBenefit.benefitsFromAnySource': 'DATA_NOT_COLLECTED',
  'IncomeBenefit.snap': null,
  'IncomeBenefit.wic': null,
  'IncomeBenefit.tanfChildCare': null,
  'IncomeBenefit.tanfTransportation': null,
  'IncomeBenefit.otherTanf': null,
  'IncomeBenefit.otherBenefitsSource': null,
};

export const EmptyInsurance = {
  'IncomeBenefit.insuranceFromAnySource': 'DATA_NOT_COLLECTED',
  'IncomeBenefit.medicaid': null,
  'IncomeBenefit.medicare': null,
  'IncomeBenefit.schip': null,
  'IncomeBenefit.vaMedicalServices': null,
  'IncomeBenefit.employerProvided': null,
  'IncomeBenefit.cobra': null,
  'IncomeBenefit.privatePay': null,
  'IncomeBenefit.stateHealthIns': null,
  'IncomeBenefit.indianHealthServices': null,
  'IncomeBenefit.otherInsurance': null,
};

export const EmptyPriorLivingSituation = {
  'Enrollment.livingSituation': null,
  'Enrollment.lengthOfStay': 'DATA_NOT_COLLECTED',
  'Enrollment.losUnderThreshold': null,
  'Enrollment.previousStreetEssh': null,
  'Enrollment.dateToStreetEssh': null,
  'Enrollment.timesHomelessPastThreeYears': 'DATA_NOT_COLLECTED',
  'Enrollment.monthsHomelessPastThreeYears': 'DATA_NOT_COLLECTED',
};

export const EmptyDisabilityGroup = {
  'DisabilityGroup.physicalDisability': 'DATA_NOT_COLLECTED',
  'DisabilityGroup.developmentalDisability': 'DATA_NOT_COLLECTED',
  'DisabilityGroup.chronicHealthCondition': 'DATA_NOT_COLLECTED',
  'DisabilityGroup.hivAids': 'DATA_NOT_COLLECTED',
  'DisabilityGroup.mentalHealthDisorder': 'DATA_NOT_COLLECTED',
  'DisabilityGroup.substanceUseDisorder': 'DATA_NOT_COLLECTED',
  'DisabilityGroup.disablingCondition': 'DATA_NOT_COLLECTED',
};

export const EmptyProjectCoc = {
  cocCode: null,
  geocode: null,
  geographyType: 'UNKNOWN_DATA_NOT_COLLECTED',
  address1: null,
  address2: null,
  city: null,
  state: 'MA',
  zip: null,
};

export const EmptyProject = {
  projectName: null,
  description: null,
  contactInformation: null,
  operatingStartDate: null,
  operatingEndDate: null,
  projectType: null,
  trackingMethod: null,
  residentialAffiliation: null,
  housingType: null,
  targetPopulation: 'NOT_APPLICABLE',
  HOPWAMedAssistedLivingFac: null,
  continuumProject: null,
  HMISParticipatingProject: null,
};
