import { PickListOption } from '@/types/gqlTypes';

export const pickListData: Record<string, PickListOption[]> = {
  SUB_TYPE_PROVIDED_3: [
    {
      label: 'VA vocational and rehabilitation counseling',
      code: 'SSVF_SERVICE__ASSISTANCE_OBTAINING_VA_BENEFITS__VA_VOCATIONAL_AND_REHABILITATION_COUNSELING',
      secondaryLabel: null,
      groupLabel: null,
      groupCode: null,
    },
    {
      label: 'Employment and training services',
      code: 'SSVF_SERVICE__ASSISTANCE_OBTAINING_VA_BENEFITS__EMPLOYMENT_AND_TRAINING_SERVICES',
      secondaryLabel: null,
      groupLabel: null,
      groupCode: null,
    },
    {
      label: 'Educational assistance',
      code: 'SSVF_SERVICE__ASSISTANCE_OBTAINING_VA_BENEFITS__EDUCATIONAL_ASSISTANCE',
      secondaryLabel: null,
      groupLabel: null,
      groupCode: null,
    },
    {
      label: 'Health care services',
      code: 'SSVF_SERVICE__ASSISTANCE_OBTAINING_VA_BENEFITS__HEALTH_CARE_SERVICES',
      secondaryLabel: null,
      groupLabel: null,
      groupCode: null,
    },
  ],
  SUB_TYPE_PROVIDED_4: [
    {
      label: 'Health care services',
      code: 'SSVF_SERVICE__ASSISTANCE_OBTAINING_COORDINATING_OTHER_PUBLIC_BENEFITS__HEALTH_CARE_SERVICES',
      secondaryLabel: null,
      groupLabel: null,
      groupCode: null,
    },
    {
      label: 'Daily living services',
      code: 'SSVF_SERVICE__ASSISTANCE_OBTAINING_COORDINATING_OTHER_PUBLIC_BENEFITS__DAILY_LIVING_SERVICES',
      secondaryLabel: null,
      groupLabel: null,
      groupCode: null,
    },
    {
      label: 'Personal financial planning services',
      code: 'SSVF_SERVICE__ASSISTANCE_OBTAINING_COORDINATING_OTHER_PUBLIC_BENEFITS__PERSONAL_FINANCIAL_PLANNING_SERVICES',
      secondaryLabel: null,
      groupLabel: null,
      groupCode: null,
    },
    {
      label: 'Transportation services',
      code: 'SSVF_SERVICE__ASSISTANCE_OBTAINING_COORDINATING_OTHER_PUBLIC_BENEFITS__TRANSPORTATION_SERVICES',
      secondaryLabel: null,
      groupLabel: null,
      groupCode: null,
    },
    {
      label: 'Income support services',
      code: 'SSVF_SERVICE__ASSISTANCE_OBTAINING_COORDINATING_OTHER_PUBLIC_BENEFITS__INCOME_SUPPORT_SERVICES',
      secondaryLabel: null,
      groupLabel: null,
      groupCode: null,
    },
    {
      label: 'Fiduciary and representative payee services',
      code: 'SSVF_SERVICE__ASSISTANCE_OBTAINING_COORDINATING_OTHER_PUBLIC_BENEFITS__FIDUCIARY_AND_REPRESENTATIVE_PAYEE_SERVICES',
      secondaryLabel: null,
      groupLabel: null,
      groupCode: null,
    },
    {
      label: 'Legal services - child support',
      code: 'SSVF_SERVICE__ASSISTANCE_OBTAINING_COORDINATING_OTHER_PUBLIC_BENEFITS__LEGAL_SERVICES_CHILD_SUPPORT',
      secondaryLabel: null,
      groupLabel: null,
      groupCode: null,
    },
    {
      label: 'Legal services - eviction prevention',
      code: 'SSVF_SERVICE__ASSISTANCE_OBTAINING_COORDINATING_OTHER_PUBLIC_BENEFITS__LEGAL_SERVICES_EVICTION_PREVENTION',
      secondaryLabel: null,
      groupLabel: null,
      groupCode: null,
    },
    {
      label: 'Legal services - outstanding fines and penalties',
      code: 'SSVF_SERVICE__ASSISTANCE_OBTAINING_COORDINATING_OTHER_PUBLIC_BENEFITS__LEGAL_SERVICES_OUTSTANDING_FINES_AND_PENALTIES',
      secondaryLabel: null,
      groupLabel: null,
      groupCode: null,
    },
    {
      label: "Legal services - restore / acquire driver's license",
      code: 'SSVF_SERVICE__ASSISTANCE_OBTAINING_COORDINATING_OTHER_PUBLIC_BENEFITS__LEGAL_SERVICES_RESTORE_ACQUIRE_DRIVER_S_LICENSE',
      secondaryLabel: null,
      groupLabel: null,
      groupCode: null,
    },
    {
      label: 'Legal services - other',
      code: 'SSVF_SERVICE__ASSISTANCE_OBTAINING_COORDINATING_OTHER_PUBLIC_BENEFITS__LEGAL_SERVICES_OTHER',
      secondaryLabel: null,
      groupLabel: null,
      groupCode: null,
    },
    {
      label: 'Child care',
      code: 'SSVF_SERVICE__ASSISTANCE_OBTAINING_COORDINATING_OTHER_PUBLIC_BENEFITS__CHILD_CARE',
      secondaryLabel: null,
      groupLabel: null,
      groupCode: null,
    },
    {
      label: 'Housing counseling',
      code: 'SSVF_SERVICE__ASSISTANCE_OBTAINING_COORDINATING_OTHER_PUBLIC_BENEFITS__HOUSING_COUNSELING',
      secondaryLabel: null,
      groupLabel: null,
      groupCode: null,
    },
  ],
  SUB_TYPE_PROVIDED_5: [
    {
      label: 'Personal financial planning services',
      code: 'SSVF_SERVICE__DIRECT_PROVISION_OF_OTHER_PUBLIC_BENEFITS__PERSONAL_FINANCIAL_PLANNING_SERVICES',
      secondaryLabel: null,
      groupLabel: null,
      groupCode: null,
    },
    {
      label: 'Transportation services',
      code: 'SSVF_SERVICE__DIRECT_PROVISION_OF_OTHER_PUBLIC_BENEFITS__TRANSPORTATION_SERVICES',
      secondaryLabel: null,
      groupLabel: null,
      groupCode: null,
    },
    {
      label: 'Income support services',
      code: 'SSVF_SERVICE__DIRECT_PROVISION_OF_OTHER_PUBLIC_BENEFITS__INCOME_SUPPORT_SERVICES',
      secondaryLabel: null,
      groupLabel: null,
      groupCode: null,
    },
    {
      label: 'Fiduciary and representative payee services',
      code: 'SSVF_SERVICE__DIRECT_PROVISION_OF_OTHER_PUBLIC_BENEFITS__FIDUCIARY_AND_REPRESENTATIVE_PAYEE_SERVICES',
      secondaryLabel: null,
      groupLabel: null,
      groupCode: null,
    },
    {
      label: 'Legal services - child support',
      code: 'SSVF_SERVICE__DIRECT_PROVISION_OF_OTHER_PUBLIC_BENEFITS__LEGAL_SERVICES_CHILD_SUPPORT',
      secondaryLabel: null,
      groupLabel: null,
      groupCode: null,
    },
    {
      label: 'Legal services - eviction prevention',
      code: 'SSVF_SERVICE__DIRECT_PROVISION_OF_OTHER_PUBLIC_BENEFITS__LEGAL_SERVICES_EVICTION_PREVENTION',
      secondaryLabel: null,
      groupLabel: null,
      groupCode: null,
    },
    {
      label: 'Legal services - outstanding fines and penalties',
      code: 'SSVF_SERVICE__DIRECT_PROVISION_OF_OTHER_PUBLIC_BENEFITS__LEGAL_SERVICES_OUTSTANDING_FINES_AND_PENALTIES',
      secondaryLabel: null,
      groupLabel: null,
      groupCode: null,
    },
    {
      label: "Legal services - restore / acquire driver's license",
      code: 'SSVF_SERVICE__DIRECT_PROVISION_OF_OTHER_PUBLIC_BENEFITS__LEGAL_SERVICES_RESTORE_ACQUIRE_DRIVER_S_LICENSE',
      secondaryLabel: null,
      groupLabel: null,
      groupCode: null,
    },
    {
      label: 'Legal services - other',
      code: 'SSVF_SERVICE__DIRECT_PROVISION_OF_OTHER_PUBLIC_BENEFITS__LEGAL_SERVICES_OTHER',
      secondaryLabel: null,
      groupLabel: null,
      groupCode: null,
    },
    {
      label: 'Child care',
      code: 'SSVF_SERVICE__DIRECT_PROVISION_OF_OTHER_PUBLIC_BENEFITS__CHILD_CARE',
      secondaryLabel: null,
      groupLabel: null,
      groupCode: null,
    },
    {
      label: 'Housing counseling',
      code: 'SSVF_SERVICE__DIRECT_PROVISION_OF_OTHER_PUBLIC_BENEFITS__HOUSING_COUNSELING',
      secondaryLabel: null,
      groupLabel: null,
      groupCode: null,
    },
  ],
  CURRENT_LIVING_SITUATION: [
    {
      label:
        'Emergency shelter, including hotel or motel paid for with emergency shelter voucher, or Host Home shelter',
      code: 'EMERGENCY_SHELTER_INCLUDING_HOTEL_OR_MOTEL_PAID_FOR_WITH_EMERGENCY_SHELTER_VOUCHER_OR_HOST_HOME_SHELTER',
      secondaryLabel: null,
      groupLabel: 'Homeless Situations',
      groupCode: 'HOMELESS',
    },
    {
      label:
        'Place not meant for habitation (e.g., a vehicle, an abandoned building, bus/train/subway station/airport or anywhere outside)',
      code: 'PLACE_NOT_MEANT_FOR_HABITATION',
      secondaryLabel: null,
      groupLabel: 'Homeless Situations',
      groupCode: 'HOMELESS',
    },
    {
      label: 'Safe Haven',
      code: 'SAFE_HAVEN',
      secondaryLabel: null,
      groupLabel: 'Homeless Situations',
      groupCode: 'HOMELESS',
    },
    {
      label: 'Psychiatric hospital or other psychiatric facility',
      code: 'PSYCHIATRIC_HOSPITAL_OR_OTHER_PSYCHIATRIC_FACILITY',
      secondaryLabel: null,
      groupLabel: 'Institutional Situations',
      groupCode: 'INSTITUTIONAL',
    },
    {
      label: 'Substance abuse treatment facility or detox center',
      code: 'SUBSTANCE_ABUSE_TREATMENT_FACILITY_OR_DETOX_CENTER',
      secondaryLabel: null,
      groupLabel: 'Institutional Situations',
      groupCode: 'INSTITUTIONAL',
    },
    {
      label: 'Hospital or other residential non-psychiatric medical facility',
      code: 'HOSPITAL_OR_OTHER_RESIDENTIAL_NON_PSYCHIATRIC_MEDICAL_FACILITY',
      secondaryLabel: null,
      groupLabel: 'Institutional Situations',
      groupCode: 'INSTITUTIONAL',
    },
    {
      label: 'Jail, prison or juvenile detention facility',
      code: 'JAIL_PRISON_OR_JUVENILE_DETENTION_FACILITY',
      secondaryLabel: null,
      groupLabel: 'Institutional Situations',
      groupCode: 'INSTITUTIONAL',
    },
    {
      label: 'Foster care home or foster care group home',
      code: 'FOSTER_CARE_HOME_OR_FOSTER_CARE_GROUP_HOME',
      secondaryLabel: null,
      groupLabel: 'Institutional Situations',
      groupCode: 'INSTITUTIONAL',
    },
    {
      label: 'Long-term care facility or nursing home',
      code: 'LONG_TERM_CARE_FACILITY_OR_NURSING_HOME',
      secondaryLabel: null,
      groupLabel: 'Institutional Situations',
      groupCode: 'INSTITUTIONAL',
    },
    {
      label:
        'Transitional housing for homeless persons (including homeless youth)',
      code: 'TRANSITIONAL_HOUSING_FOR_HOMELESS_PERSONS',
      secondaryLabel: null,
      groupLabel: 'Temporary Housing Situations',
      groupCode: 'TEMPORARY',
    },
    {
      label: 'Hotel or motel paid for without emergency shelter voucher',
      code: 'HOTEL_OR_MOTEL_PAID_FOR_WITHOUT_EMERGENCY_SHELTER_VOUCHER',
      secondaryLabel: null,
      groupLabel: 'Temporary Housing Situations',
      groupCode: 'TEMPORARY',
    },
    {
      label: 'Residential project or halfway house with no homeless criteria',
      code: 'RESIDENTIAL_PROJECT_OR_HALFWAY_HOUSE_WITH_NO_HOMELESS_CRITERIA',
      secondaryLabel: null,
      groupLabel: 'Temporary Housing Situations',
      groupCode: 'TEMPORARY',
    },
    {
      label: 'Host Home (non-crisis)',
      code: 'HOST_HOME_NON_CRISIS',
      secondaryLabel: null,
      groupLabel: 'Temporary Housing Situations',
      groupCode: 'TEMPORARY',
    },
    {
      label: 'Staying or living in a family member’s room, apartment, or house',
      code: 'STAYING_OR_LIVING_IN_A_FAMILY_MEMBER_S_ROOM_APARTMENT_OR_HOUSE',
      secondaryLabel: null,
      groupLabel: 'Temporary Housing Situations',
      groupCode: 'TEMPORARY',
    },
    {
      label: "Staying or living in a friend's room, apartment or house",
      code: 'STAYING_OR_LIVING_IN_A_FRIEND_S_ROOM_APARTMENT_OR_HOUSE',
      secondaryLabel: null,
      groupLabel: 'Temporary Housing Situations',
      groupCode: 'TEMPORARY',
    },
    {
      label: 'Rental by client, no ongoing housing subsidy',
      code: 'RENTAL_BY_CLIENT_NO_ONGOING_HOUSING_SUBSIDY',
      secondaryLabel: null,
      groupLabel: 'Permanent Housing Situations',
      groupCode: 'PERMANENT',
    },
    {
      label: 'Owned by client, no ongoing housing subsidy',
      code: 'OWNED_BY_CLIENT_NO_ONGOING_HOUSING_SUBSIDY',
      secondaryLabel: null,
      groupLabel: 'Permanent Housing Situations',
      groupCode: 'PERMANENT',
    },
    {
      label: 'Owned by client, with ongoing housing subsidy',
      code: 'OWNED_BY_CLIENT_WITH_ONGOING_HOUSING_SUBSIDY',
      secondaryLabel: null,
      groupLabel: 'Permanent Housing Situations',
      groupCode: 'PERMANENT',
    },
    {
      label: 'Rental by client, with ongoing housing subsidy',
      code: 'RENTAL_BY_CLIENT_WITH_ONGOING_HOUSING_SUBSIDY',
      secondaryLabel: null,
      groupLabel: 'Permanent Housing Situations',
      groupCode: 'PERMANENT',
    },
    {
      label: "Client doesn't know",
      code: 'CLIENT_DOESN_T_KNOW',
      secondaryLabel: null,
      groupLabel: 'Other',
      groupCode: 'OTHER',
    },
    {
      label: 'Client prefers not to answer',
      code: 'CLIENT_PREFERS_NOT_TO_ANSWER',
      secondaryLabel: null,
      groupLabel: 'Other',
      groupCode: 'OTHER',
    },
    {
      label: 'Other',
      code: 'OTHER',
      secondaryLabel: null,
      groupLabel: 'Other',
      groupCode: 'OTHER',
    },
    {
      label: 'Worker unable to determine',
      code: 'WORKER_UNABLE_TO_DETERMINE',
      secondaryLabel: null,
      groupLabel: 'Other',
      groupCode: 'OTHER',
    },
    {
      label: 'Data not collected',
      code: 'DATA_NOT_COLLECTED',
      secondaryLabel: null,
      groupLabel: 'Other',
      groupCode: 'OTHER',
    },
  ],
};
