import { gql } from '@apollo/client';
import * as Apollo from '@apollo/client';
export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = {
  [K in keyof T]: T[K];
};
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & {
  [SubKey in K]?: Maybe<T[SubKey]>;
};
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & {
  [SubKey in K]: Maybe<T[SubKey]>;
};
const defaultOptions = {} as const;
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: string;
  String: string;
  Boolean: boolean;
  Int: number;
  Float: number;
  /** An ISO 8601-encoded date */
  ISO8601Date: string;
  /** An ISO 8601-encoded datetime */
  ISO8601DateTime: string;
  /** Arbitrary JSON Type */
  JsonObject: any;
};

/** HUD Assessment */
export type Assessment = {
  __typename?: 'Assessment';
  assessmentDate: Scalars['ISO8601DateTime'];
  assessmentLevel: AssessmentLevel;
  assessmentLocation: Scalars['String'];
  assessmentType: AssessmentType;
  client: Client;
  dateCreated: Scalars['ISO8601DateTime'];
  dateDeleted: Scalars['ISO8601DateTime'];
  dateUpdated: Scalars['ISO8601DateTime'];
  enrollment: Enrollment;
  id: Scalars['ID'];
  prioritizationStatus: PrioritizationStatus;
};

/** HUD AssessmentLevel */
export enum AssessmentLevel {
  /** Crisis Needs Assessment */
  CrisisNeedsAssessment = 'CRISIS_NEEDS_ASSESSMENT',
  /** Housing Needs Assessment */
  HousingNeedsAssessment = 'HOUSING_NEEDS_ASSESSMENT',
}

/** HUD AssessmentType */
export enum AssessmentType {
  /** In Person */
  InPerson = 'IN_PERSON',
  /** Phone */
  Phone = 'PHONE',
  /** Virtual */
  Virtual = 'VIRTUAL',
}

export type AssessmentsPaginated = {
  __typename?: 'AssessmentsPaginated';
  hasMoreAfter: Scalars['Boolean'];
  hasMoreBefore: Scalars['Boolean'];
  limit: Scalars['Int'];
  nodes: Array<Assessment>;
  nodesCount: Scalars['Int'];
  offset: Scalars['Int'];
  pagesCount: Scalars['Int'];
};

/** HUD Client */
export type Client = {
  __typename?: 'Client';
  dateUpdated: Scalars['ISO8601DateTime'];
  /** Date of birth as format yyyy-mm-dd */
  dob?: Maybe<Scalars['ISO8601Date']>;
  enrollments: EnrollmentsPaginated;
  firstName?: Maybe<Scalars['String']>;
  id: Scalars['ID'];
  lastName?: Maybe<Scalars['String']>;
  nameSuffix?: Maybe<Scalars['String']>;
  personalId: Scalars['String'];
  preferredName?: Maybe<Scalars['String']>;
  pronouns?: Maybe<Scalars['String']>;
  ssnSerial?: Maybe<Scalars['String']>;
};

/** HUD Client */
export type ClientEnrollmentsArgs = {
  limit?: InputMaybe<Scalars['Int']>;
  offset?: InputMaybe<Scalars['Int']>;
  sortOrder?: InputMaybe<EnrollmentSortOption>;
};

/** HMIS Client input */
export type ClientInput = {
  dob?: InputMaybe<Scalars['String']>;
  dobQuality?: InputMaybe<DobDataQuality>;
  ethnicity?: InputMaybe<Ethnicity>;
  firstName?: InputMaybe<Scalars['String']>;
  gender?: InputMaybe<Array<Gender>>;
  lastName?: InputMaybe<Scalars['String']>;
  middleName?: InputMaybe<Scalars['String']>;
  nameQuality?: InputMaybe<NameDataQuality>;
  nameSuffix?: InputMaybe<Scalars['String']>;
  preferredName?: InputMaybe<Scalars['String']>;
  race?: InputMaybe<Array<Race>>;
  ssn?: InputMaybe<Scalars['String']>;
  ssnQuality?: InputMaybe<SsnDataQuality>;
  veteranStatus?: InputMaybe<VeteranStatus>;
};

/** HMIS Client search input */
export type ClientSearchInput = {
  /** Date of birth as format yyyy-mm-dd */
  dob?: InputMaybe<Scalars['String']>;
  firstName?: InputMaybe<Scalars['String']>;
  /** Client primary key */
  id?: InputMaybe<Scalars['ID']>;
  lastName?: InputMaybe<Scalars['String']>;
  organizations?: InputMaybe<Array<Scalars['ID']>>;
  personalId?: InputMaybe<Scalars['String']>;
  preferredName?: InputMaybe<Scalars['String']>;
  projects?: InputMaybe<Array<Scalars['ID']>>;
  /** Last 4 digits of SSN */
  ssnSerial?: InputMaybe<Scalars['String']>;
  /** Omnisearch string */
  textSearch?: InputMaybe<Scalars['String']>;
  warehouseId?: InputMaybe<Scalars['String']>;
};

/** HUD Client Sorting Options */
export enum ClientSortOption {
  LastNameAsc = 'LAST_NAME_ASC',
  LastNameDesc = 'LAST_NAME_DESC',
}

export type ClientsPaginated = {
  __typename?: 'ClientsPaginated';
  hasMoreAfter: Scalars['Boolean'];
  hasMoreBefore: Scalars['Boolean'];
  limit: Scalars['Int'];
  nodes: Array<Client>;
  nodesCount: Scalars['Int'];
  offset: Scalars['Int'];
  pagesCount: Scalars['Int'];
};

/** Autogenerated input type of CreateClient */
export type CreateClientInput = {
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: InputMaybe<Scalars['String']>;
  input: ClientInput;
};

/** Autogenerated return type of CreateClient */
export type CreateClientPayload = {
  __typename?: 'CreateClientPayload';
  client?: Maybe<Client>;
  /** A unique identifier for the client performing the mutation. */
  clientMutationId?: Maybe<Scalars['String']>;
  errors: Array<ValidationError>;
};

/** HUD DOB Data Quality */
export enum DobDataQuality {
  /** Full DOB reported */
  DobFull = 'DOB_FULL',
  /** Data not collected */
  DobNotCollected = 'DOB_NOT_COLLECTED',
  /** Full DOB reported */
  DobPartial = 'DOB_PARTIAL',
  /** Client refused */
  DobRefused = 'DOB_REFUSED',
  /** Client doesn't know */
  DobUnknown = 'DOB_UNKNOWN',
}

/** HUD Enrollment */
export type Enrollment = {
  __typename?: 'Enrollment';
  assessments: AssessmentsPaginated;
  entryDate?: Maybe<Scalars['ISO8601DateTime']>;
  events: EventsPaginated;
  exitDate?: Maybe<Scalars['ISO8601DateTime']>;
  household?: Maybe<Household>;
  id: Scalars['ID'];
  project: Project;
  services: ServicesPaginated;
};

/** HUD Enrollment */
export type EnrollmentAssessmentsArgs = {
  limit?: InputMaybe<Scalars['Int']>;
  offset?: InputMaybe<Scalars['Int']>;
};

/** HUD Enrollment */
export type EnrollmentEventsArgs = {
  limit?: InputMaybe<Scalars['Int']>;
  offset?: InputMaybe<Scalars['Int']>;
};

/** HUD Enrollment */
export type EnrollmentServicesArgs = {
  limit?: InputMaybe<Scalars['Int']>;
  offset?: InputMaybe<Scalars['Int']>;
};

/** HUD Enrollment Sorting Options */
export enum EnrollmentSortOption {
  MostRecent = 'MOST_RECENT',
}

export type EnrollmentsPaginated = {
  __typename?: 'EnrollmentsPaginated';
  hasMoreAfter: Scalars['Boolean'];
  hasMoreBefore: Scalars['Boolean'];
  limit: Scalars['Int'];
  nodes: Array<Enrollment>;
  nodesCount: Scalars['Int'];
  offset: Scalars['Int'];
  pagesCount: Scalars['Int'];
};

/** HUD Ethnicity */
export enum Ethnicity {
  /** Hispanic/Latin(a)(o)(x) */
  EthnicityHispanic = 'ETHNICITY_HISPANIC',
  /** Non-Hispanic/Non-Latin(a)(o)(x) */
  EthnicityNonHispanic = 'ETHNICITY_NON_HISPANIC',
  /** Data not collected */
  EthnicityNotCollected = 'ETHNICITY_NOT_COLLECTED',
  /** Client refused */
  EthnicityRefused = 'ETHNICITY_REFUSED',
  /** Client doesn't know */
  EthnicityUnknown = 'ETHNICITY_UNKNOWN',
}

/** HUD Event */
export type Event = {
  __typename?: 'Event';
  client: Client;
  dateCreated: Scalars['ISO8601DateTime'];
  dateDeleted: Scalars['ISO8601DateTime'];
  dateUpdated: Scalars['ISO8601DateTime'];
  enrollment: Enrollment;
  event: EventType;
  eventDate: Scalars['ISO8601DateTime'];
  id: Scalars['ID'];
  locationCrisisOrPhHousing?: Maybe<Scalars['String']>;
  probSolDivRrResult?: Maybe<ProbSolDivRrResult>;
  referralCaseManageAfter?: Maybe<ReferralCaseManageAfter>;
  referralResult?: Maybe<ReferralResult>;
  resultDate?: Maybe<Scalars['ISO8601DateTime']>;
};

/** HUD EventType */
export enum EventType {
  /** Problem Solving/Diversion/Rapid Resolution intervention or service */
  ProblemSolvingDiversionRapidResolutionInterventionOrService = 'PROBLEM_SOLVING_DIVERSION_RAPID_RESOLUTION_INTERVENTION_OR_SERVICE',
  /** Referral to a Housing Stability Voucher */
  ReferralToAHousingStabilityVoucher = 'REFERRAL_TO_A_HOUSING_STABILITY_VOUCHER',
  /** Referral to emergency assistance/flex fund/furniture assistance */
  ReferralToEmergencyAssistanceFlexFundFurnitureAssistance = 'REFERRAL_TO_EMERGENCY_ASSISTANCE_FLEX_FUND_FURNITURE_ASSISTANCE',
  /** Referral to Emergency Housing Voucher (EHV) */
  ReferralToEmergencyHousingVoucherEhv = 'REFERRAL_TO_EMERGENCY_HOUSING_VOUCHER_EHV_',
  /** Referral to Emergency Shelter bed opening */
  ReferralToEmergencyShelterBedOpening = 'REFERRAL_TO_EMERGENCY_SHELTER_BED_OPENING',
  /** Referral to Housing Navigation project or services */
  ReferralToHousingNavigationProjectOrServices = 'REFERRAL_TO_HOUSING_NAVIGATION_PROJECT_OR_SERVICES',
  /** Referral to Joint TH-RRH project/unit/resource opening */
  ReferralToJointThRrhProjectUnitResourceOpening = 'REFERRAL_TO_JOINT_TH_RRH_PROJECT_UNIT_RESOURCE_OPENING',
  /** Referral to Non-continuum services: Ineligible for continuum services */
  ReferralToNonContinuumServicesIneligibleForContinuumServices = 'REFERRAL_TO_NON_CONTINUUM_SERVICES_INELIGIBLE_FOR_CONTINUUM_SERVICES',
  /** Referral to Non-continuum services: No availability in continuum services */
  ReferralToNonContinuumServicesNoAvailabilityInContinuumServices = 'REFERRAL_TO_NON_CONTINUUM_SERVICES_NO_AVAILABILITY_IN_CONTINUUM_SERVICES',
  /** Referral to Other PH project/unit/resource opening */
  ReferralToOtherPhProjectUnitResourceOpening = 'REFERRAL_TO_OTHER_PH_PROJECT_UNIT_RESOURCE_OPENING',
  /** Referral to Post-placement/ follow-up case management */
  ReferralToPostPlacementFollowUpCaseManagement = 'REFERRAL_TO_POST_PLACEMENT_FOLLOW_UP_CASE_MANAGEMENT',
  /** Referral to Prevention Assistance project */
  ReferralToPreventionAssistanceProject = 'REFERRAL_TO_PREVENTION_ASSISTANCE_PROJECT',
  /** Referral to PSH project resource opening */
  ReferralToPshProjectResourceOpening = 'REFERRAL_TO_PSH_PROJECT_RESOURCE_OPENING',
  /** Referral to RRH project resource opening */
  ReferralToRrhProjectResourceOpening = 'REFERRAL_TO_RRH_PROJECT_RESOURCE_OPENING',
  /** Referral to scheduled Coordinated Entry Crisis Needs Assessment */
  ReferralToScheduledCoordinatedEntryCrisisNeedsAssessment = 'REFERRAL_TO_SCHEDULED_COORDINATED_ENTRY_CRISIS_NEEDS_ASSESSMENT',
  /** Referral to scheduled Coordinated Entry Housing Needs Assessment */
  ReferralToScheduledCoordinatedEntryHousingNeedsAssessment = 'REFERRAL_TO_SCHEDULED_COORDINATED_ENTRY_HOUSING_NEEDS_ASSESSMENT',
  /** Referral to Street Outreach project or services */
  ReferralToStreetOutreachProjectOrServices = 'REFERRAL_TO_STREET_OUTREACH_PROJECT_OR_SERVICES',
  /** Referral to Transitional Housing bed/unit opening */
  ReferralToTransitionalHousingBedUnitOpening = 'REFERRAL_TO_TRANSITIONAL_HOUSING_BED_UNIT_OPENING',
}

export type EventsPaginated = {
  __typename?: 'EventsPaginated';
  hasMoreAfter: Scalars['Boolean'];
  hasMoreBefore: Scalars['Boolean'];
  limit: Scalars['Int'];
  nodes: Array<Event>;
  nodesCount: Scalars['Int'];
  offset: Scalars['Int'];
  pagesCount: Scalars['Int'];
};

/** HUD Gender */
export enum Gender {
  /** Female */
  GenderFemale = 'GENDER_FEMALE',
  /** Male */
  GenderMale = 'GENDER_MALE',
  /** Data not collected */
  GenderNotCollected = 'GENDER_NOT_COLLECTED',
  /** A gender other than singularly female or male (e.g., non-binary, genderfluid, agender, culturally specific gender) */
  GenderNoSingleGender = 'GENDER_NO_SINGLE_GENDER',
  /** Questioning */
  GenderQuestioning = 'GENDER_QUESTIONING',
  /** Client refused */
  GenderRefused = 'GENDER_REFUSED',
  /** Transgender */
  GenderTransgender = 'GENDER_TRANSGENDER',
  /** Client doesn't know */
  GenderUnknown = 'GENDER_UNKNOWN',
}

/** HUD Household */
export type Household = {
  __typename?: 'Household';
  householdClients: Array<HouseholdClient>;
  id: Scalars['ID'];
};

/** HUD Client within a Household */
export type HouseholdClient = {
  __typename?: 'HouseholdClient';
  client: Client;
  id: Scalars['ID'];
  relationshipToHoH: Scalars['String'];
};

export type Mutation = {
  __typename?: 'Mutation';
  createClient?: Maybe<CreateClientPayload>;
};

export type MutationCreateClientArgs = {
  input: CreateClientInput;
};

/** HUD Name Data Quality */
export enum NameDataQuality {
  /** Full name reported */
  NameFull = 'NAME_FULL',
  /** Data not collected */
  NameNotCollected = 'NAME_NOT_COLLECTED',
  /** Partial, street name, or code name reported */
  NamePartial = 'NAME_PARTIAL',
  /** Client refused */
  NameRefused = 'NAME_REFUSED',
  /** Client doesn't know */
  NameUnknown = 'NAME_UNKNOWN',
}

/** HUD Organization */
export type Organization = {
  __typename?: 'Organization';
  id: Scalars['ID'];
  organizationName: Scalars['String'];
  /** Get a list of projects for this organization */
  projects: Array<Project>;
};

/** HUD Organization */
export type OrganizationProjectsArgs = {
  projectTypes?: InputMaybe<Array<ProjectType>>;
  sortOrder?: InputMaybe<ProjectSortOption>;
};

/** HUD Organization Sorting Options */
export enum OrganizationSortOption {
  Name = 'NAME',
}

/** HUD PrioritizationStatus */
export enum PrioritizationStatus {
  /** Not placed on prioritization list */
  NotPlacedOnPrioritizationList = 'NOT_PLACED_ON_PRIORITIZATION_LIST',
  /** Placed on prioritization list */
  PlacedOnPrioritizationList = 'PLACED_ON_PRIORITIZATION_LIST',
}

/** HUD ProbSolDivRRResult */
export enum ProbSolDivRrResult {
  /** Data not collected* */
  DataNotCollected = 'DATA_NOT_COLLECTED_',
  /** No */
  No = 'NO',
  /** Yes */
  Yes = 'YES',
}

/** HUD Project */
export type Project = {
  __typename?: 'Project';
  id: Scalars['ID'];
  organization: Organization;
  projectName: Scalars['String'];
  projectType: ProjectType;
};

/** HUD Project Sorting Options */
export enum ProjectSortOption {
  Name = 'NAME',
  OrganizationAndName = 'ORGANIZATION_AND_NAME',
}

/** HUD Project Types */
export enum ProjectType {
  /** Coordinated Entry */
  Ce = 'CE',
  /** Day Shelter */
  DayShelter = 'DAY_SHELTER',
  /** Emergency Shelter */
  Es = 'ES',
  /** Permanent Housing Only */
  Oph = 'OPH',
  /** Other */
  Other = 'OTHER',
  /** Permanent Housing */
  Ph = 'PH',
  /** Homelessness Prevention */
  Prevention = 'PREVENTION',
  /** Permanent Supportive Housing */
  Psh = 'PSH',
  /** Rapid Re-Housing */
  Rrh = 'RRH',
  /** Services Only */
  ServicesOnly = 'SERVICES_ONLY',
  /** Safe Haven */
  Sh = 'SH',
  /** Street Outreach */
  So = 'SO',
  /** Transitional Housing */
  Th = 'TH',
}

export type Query = {
  __typename?: 'Query';
  /** Client lookup */
  client?: Maybe<Client>;
  /** Search for clients */
  clientSearch: ClientsPaginated;
  /** Enrollment lookup */
  enrollment?: Maybe<Enrollment>;
  /** Get a list of organizations */
  organizations: Array<Organization>;
  /** Get a list of projects */
  projects: Array<Project>;
};

export type QueryClientArgs = {
  id: Scalars['ID'];
};

export type QueryClientSearchArgs = {
  input: ClientSearchInput;
  limit?: InputMaybe<Scalars['Int']>;
  offset?: InputMaybe<Scalars['Int']>;
  sortOrder?: InputMaybe<ClientSortOption>;
};

export type QueryEnrollmentArgs = {
  id: Scalars['ID'];
};

export type QueryOrganizationsArgs = {
  sortOrder?: InputMaybe<OrganizationSortOption>;
};

export type QueryProjectsArgs = {
  projectTypes?: InputMaybe<Array<ProjectType>>;
  sortOrder?: InputMaybe<ProjectSortOption>;
};

/** HUD Race */
export enum Race {
  /** American Indian, Alaska Native, or Indigenous */
  RaceAmIndAkNative = 'RACE_AM_IND_AK_NATIVE',
  /** Asian or Asian American */
  RaceAsian = 'RACE_ASIAN',
  /** Black, African American, or African */
  RaceBlackAfAmerican = 'RACE_BLACK_AF_AMERICAN',
  /** Native Hawaiian or Pacific Islander */
  RaceNativeHiPacific = 'RACE_NATIVE_HI_PACIFIC',
  /** Data not collected */
  RaceNotCollected = 'RACE_NOT_COLLECTED',
  /** Client refused */
  RaceRefused = 'RACE_REFUSED',
  /** Client doesn't know */
  RaceUnknown = 'RACE_UNKNOWN',
  /** White */
  RaceWhite = 'RACE_WHITE',
}

/** HUD ReferralCaseManageAfter */
export enum ReferralCaseManageAfter {
  /** Data not collected* */
  DataNotCollected = 'DATA_NOT_COLLECTED_',
  /** No */
  No = 'NO',
  /** Yes */
  Yes = 'YES',
}

/** HUD ReferralResult */
export enum ReferralResult {
  /** Successful referral: client accepted */
  SuccessfulReferralClientAccepted = 'SUCCESSFUL_REFERRAL_CLIENT_ACCEPTED',
  /** Unsuccessful referral: client rejected */
  UnsuccessfulReferralClientRejected = 'UNSUCCESSFUL_REFERRAL_CLIENT_REJECTED',
  /** Unsuccessful referral: provider rejected */
  UnsuccessfulReferralProviderRejected = 'UNSUCCESSFUL_REFERRAL_PROVIDER_REJECTED',
}

/** HUD SSN Data Quality */
export enum SsnDataQuality {
  /** Full SSN reported */
  SsnFull = 'SSN_FULL',
  /** Data not collected */
  SsnNotCollected = 'SSN_NOT_COLLECTED',
  /** Approximate or partial SSN reported */
  SsnPartial = 'SSN_PARTIAL',
  /** Client refused */
  SsnRefused = 'SSN_REFUSED',
  /** Client doesn't know */
  SsnUnknown = 'SSN_UNKNOWN',
}

/** HUD Service */
export type Service = {
  __typename?: 'Service';
  id: Scalars['ID'];
};

export type ServicesPaginated = {
  __typename?: 'ServicesPaginated';
  hasMoreAfter: Scalars['Boolean'];
  hasMoreBefore: Scalars['Boolean'];
  limit: Scalars['Int'];
  nodes: Array<Service>;
  nodesCount: Scalars['Int'];
  offset: Scalars['Int'];
  pagesCount: Scalars['Int'];
};

export type ValidationError = {
  __typename?: 'ValidationError';
  attribute?: Maybe<Scalars['String']>;
  fullMessage?: Maybe<Scalars['String']>;
  message: Scalars['String'];
  options?: Maybe<Scalars['JsonObject']>;
  type: Scalars['String'];
};

/** HUD Veteran Status */
export enum VeteranStatus {
  /** Client doesn't know */
  VeteranStatusClientDoesnTKnow = 'VETERAN_STATUS_CLIENT_DOESN_T_KNOW',
  /** Client refused */
  VeteranStatusClientRefused = 'VETERAN_STATUS_CLIENT_REFUSED',
  /** Data not collected */
  VeteranStatusDataNotCollected = 'VETERAN_STATUS_DATA_NOT_COLLECTED',
  /** No */
  VeteranStatusNo = 'VETERAN_STATUS_NO',
  /** Yes */
  VeteranStatusYes = 'VETERAN_STATUS_YES',
}

export type EnrollmentFieldsFragment = {
  __typename?: 'Enrollment';
  id: string;
  entryDate?: string | null;
  exitDate?: string | null;
  project: { __typename?: 'Project'; projectName: string };
};

export type ClientNameFragment = {
  __typename?: 'Client';
  firstName?: string | null;
  preferredName?: string | null;
  lastName?: string | null;
  nameSuffix?: string | null;
};

export type ClientFieldsFragment = {
  __typename?: 'Client';
  id: string;
  personalId: string;
  ssnSerial?: string | null;
  dob?: string | null;
  dateUpdated: string;
  firstName?: string | null;
  preferredName?: string | null;
  lastName?: string | null;
  nameSuffix?: string | null;
};

export type HouseholdClientFieldsFragment = {
  __typename?: 'HouseholdClient';
  id: string;
  relationshipToHoH: string;
  client: {
    __typename?: 'Client';
    id: string;
    firstName?: string | null;
    preferredName?: string | null;
    lastName?: string | null;
    nameSuffix?: string | null;
  };
};

export type GetEnrollmentQueryVariables = Exact<{
  id: Scalars['ID'];
}>;

export type GetEnrollmentQuery = {
  __typename?: 'Query';
  enrollment?: {
    __typename?: 'Enrollment';
    id: string;
    entryDate?: string | null;
    exitDate?: string | null;
    project: { __typename?: 'Project'; projectName: string };
  } | null;
};

export type GetEnrollmentWithHoHQueryVariables = Exact<{
  id: Scalars['ID'];
}>;

export type GetEnrollmentWithHoHQuery = {
  __typename?: 'Query';
  enrollment?: {
    __typename?: 'Enrollment';
    id: string;
    entryDate?: string | null;
    exitDate?: string | null;
    household?: {
      __typename?: 'Household';
      id: string;
      householdClients: Array<{
        __typename?: 'HouseholdClient';
        id: string;
        relationshipToHoH: string;
        client: {
          __typename?: 'Client';
          id: string;
          firstName?: string | null;
          preferredName?: string | null;
          lastName?: string | null;
          nameSuffix?: string | null;
        };
      }>;
    } | null;
    project: { __typename?: 'Project'; projectName: string };
  } | null;
};

export type SearchClientsQueryVariables = Exact<{
  input: ClientSearchInput;
  limit?: InputMaybe<Scalars['Int']>;
  offset?: InputMaybe<Scalars['Int']>;
}>;

export type SearchClientsQuery = {
  __typename?: 'Query';
  clientSearch: {
    __typename?: 'ClientsPaginated';
    offset: number;
    limit: number;
    nodesCount: number;
    nodes: Array<{
      __typename?: 'Client';
      id: string;
      personalId: string;
      ssnSerial?: string | null;
      dob?: string | null;
      dateUpdated: string;
      firstName?: string | null;
      preferredName?: string | null;
      lastName?: string | null;
      nameSuffix?: string | null;
    }>;
  };
};

export type GetClientQueryVariables = Exact<{
  id: Scalars['ID'];
}>;

export type GetClientQuery = {
  __typename?: 'Query';
  client?: {
    __typename?: 'Client';
    id: string;
    personalId: string;
    ssnSerial?: string | null;
    dob?: string | null;
    dateUpdated: string;
    firstName?: string | null;
    preferredName?: string | null;
    lastName?: string | null;
    nameSuffix?: string | null;
  } | null;
};

export type GetClientWithEnrollmentsQueryVariables = Exact<{
  id: Scalars['ID'];
  enrollmentsLimit?: InputMaybe<Scalars['Int']>;
  enrollmentsOffset?: InputMaybe<Scalars['Int']>;
}>;

export type GetClientWithEnrollmentsQuery = {
  __typename?: 'Query';
  client?: {
    __typename?: 'Client';
    id: string;
    personalId: string;
    ssnSerial?: string | null;
    dob?: string | null;
    dateUpdated: string;
    firstName?: string | null;
    preferredName?: string | null;
    lastName?: string | null;
    nameSuffix?: string | null;
    enrollments: {
      __typename?: 'EnrollmentsPaginated';
      offset: number;
      limit: number;
      nodesCount: number;
      nodes: Array<{
        __typename?: 'Enrollment';
        id: string;
        entryDate?: string | null;
        exitDate?: string | null;
        project: { __typename?: 'Project'; projectName: string };
      }>;
    };
  } | null;
};

export type CreateClientMutationVariables = Exact<{
  input: CreateClientInput;
}>;

export type CreateClientMutation = {
  __typename?: 'Mutation';
  createClient?: {
    __typename?: 'CreateClientPayload';
    clientMutationId?: string | null;
    client?: {
      __typename?: 'Client';
      id: string;
      personalId: string;
      ssnSerial?: string | null;
      dob?: string | null;
      dateUpdated: string;
      firstName?: string | null;
      preferredName?: string | null;
      lastName?: string | null;
      nameSuffix?: string | null;
    } | null;
    errors: Array<{
      __typename?: 'ValidationError';
      type: string;
      attribute?: string | null;
      message: string;
      fullMessage?: string | null;
    }>;
  } | null;
};

export type ProjectFieldsFragment = {
  __typename?: 'Project';
  id: string;
  projectName: string;
  projectType: ProjectType;
};

export type OrganizationFieldsFragment = {
  __typename?: 'Organization';
  id: string;
  organizationName: string;
};

export type GetProjectsForSelectQueryVariables = Exact<{
  [key: string]: never;
}>;

export type GetProjectsForSelectQuery = {
  __typename?: 'Query';
  projects: Array<{
    __typename?: 'Project';
    id: string;
    projectName: string;
    projectType: ProjectType;
    organization: { __typename?: 'Organization'; organizationName: string };
  }>;
};

export type GetOrganizationsForSelectQueryVariables = Exact<{
  [key: string]: never;
}>;

export type GetOrganizationsForSelectQuery = {
  __typename?: 'Query';
  organizations: Array<{
    __typename?: 'Organization';
    id: string;
    organizationName: string;
  }>;
};

export const EnrollmentFieldsFragmentDoc = gql`
  fragment EnrollmentFields on Enrollment {
    id
    entryDate
    exitDate
    project {
      projectName
    }
  }
`;
export const ClientNameFragmentDoc = gql`
  fragment ClientName on Client {
    firstName
    preferredName
    lastName
    nameSuffix
  }
`;
export const ClientFieldsFragmentDoc = gql`
  fragment ClientFields on Client {
    id
    personalId
    ssnSerial
    dob
    dateUpdated
    ...ClientName
  }
  ${ClientNameFragmentDoc}
`;
export const HouseholdClientFieldsFragmentDoc = gql`
  fragment HouseholdClientFields on HouseholdClient {
    id
    relationshipToHoH
    client {
      id
      ...ClientName
    }
  }
  ${ClientNameFragmentDoc}
`;
export const ProjectFieldsFragmentDoc = gql`
  fragment ProjectFields on Project {
    id
    projectName
    projectType
  }
`;
export const OrganizationFieldsFragmentDoc = gql`
  fragment OrganizationFields on Organization {
    id
    organizationName
  }
`;
export const GetEnrollmentDocument = gql`
  query GetEnrollment($id: ID!) {
    enrollment(id: $id) {
      ...EnrollmentFields
    }
  }
  ${EnrollmentFieldsFragmentDoc}
`;

/**
 * __useGetEnrollmentQuery__
 *
 * To run a query within a React component, call `useGetEnrollmentQuery` and pass it any options that fit your needs.
 * When your component renders, `useGetEnrollmentQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useGetEnrollmentQuery({
 *   variables: {
 *      id: // value for 'id'
 *   },
 * });
 */
export function useGetEnrollmentQuery(
  baseOptions: Apollo.QueryHookOptions<
    GetEnrollmentQuery,
    GetEnrollmentQueryVariables
  >
) {
  const options = { ...defaultOptions, ...baseOptions };
  return Apollo.useQuery<GetEnrollmentQuery, GetEnrollmentQueryVariables>(
    GetEnrollmentDocument,
    options
  );
}
export function useGetEnrollmentLazyQuery(
  baseOptions?: Apollo.LazyQueryHookOptions<
    GetEnrollmentQuery,
    GetEnrollmentQueryVariables
  >
) {
  const options = { ...defaultOptions, ...baseOptions };
  return Apollo.useLazyQuery<GetEnrollmentQuery, GetEnrollmentQueryVariables>(
    GetEnrollmentDocument,
    options
  );
}
export type GetEnrollmentQueryHookResult = ReturnType<
  typeof useGetEnrollmentQuery
>;
export type GetEnrollmentLazyQueryHookResult = ReturnType<
  typeof useGetEnrollmentLazyQuery
>;
export type GetEnrollmentQueryResult = Apollo.QueryResult<
  GetEnrollmentQuery,
  GetEnrollmentQueryVariables
>;
export const GetEnrollmentWithHoHDocument = gql`
  query GetEnrollmentWithHoH($id: ID!) {
    enrollment(id: $id) {
      ...EnrollmentFields
      household {
        id
        householdClients {
          ...HouseholdClientFields
        }
      }
    }
  }
  ${EnrollmentFieldsFragmentDoc}
  ${HouseholdClientFieldsFragmentDoc}
`;

/**
 * __useGetEnrollmentWithHoHQuery__
 *
 * To run a query within a React component, call `useGetEnrollmentWithHoHQuery` and pass it any options that fit your needs.
 * When your component renders, `useGetEnrollmentWithHoHQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useGetEnrollmentWithHoHQuery({
 *   variables: {
 *      id: // value for 'id'
 *   },
 * });
 */
export function useGetEnrollmentWithHoHQuery(
  baseOptions: Apollo.QueryHookOptions<
    GetEnrollmentWithHoHQuery,
    GetEnrollmentWithHoHQueryVariables
  >
) {
  const options = { ...defaultOptions, ...baseOptions };
  return Apollo.useQuery<
    GetEnrollmentWithHoHQuery,
    GetEnrollmentWithHoHQueryVariables
  >(GetEnrollmentWithHoHDocument, options);
}
export function useGetEnrollmentWithHoHLazyQuery(
  baseOptions?: Apollo.LazyQueryHookOptions<
    GetEnrollmentWithHoHQuery,
    GetEnrollmentWithHoHQueryVariables
  >
) {
  const options = { ...defaultOptions, ...baseOptions };
  return Apollo.useLazyQuery<
    GetEnrollmentWithHoHQuery,
    GetEnrollmentWithHoHQueryVariables
  >(GetEnrollmentWithHoHDocument, options);
}
export type GetEnrollmentWithHoHQueryHookResult = ReturnType<
  typeof useGetEnrollmentWithHoHQuery
>;
export type GetEnrollmentWithHoHLazyQueryHookResult = ReturnType<
  typeof useGetEnrollmentWithHoHLazyQuery
>;
export type GetEnrollmentWithHoHQueryResult = Apollo.QueryResult<
  GetEnrollmentWithHoHQuery,
  GetEnrollmentWithHoHQueryVariables
>;
export const SearchClientsDocument = gql`
  query SearchClients($input: ClientSearchInput!, $limit: Int, $offset: Int) {
    clientSearch(input: $input, limit: $limit, offset: $offset) {
      offset
      limit
      nodesCount
      nodes {
        ...ClientFields
      }
    }
  }
  ${ClientFieldsFragmentDoc}
`;

/**
 * __useSearchClientsQuery__
 *
 * To run a query within a React component, call `useSearchClientsQuery` and pass it any options that fit your needs.
 * When your component renders, `useSearchClientsQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useSearchClientsQuery({
 *   variables: {
 *      input: // value for 'input'
 *      limit: // value for 'limit'
 *      offset: // value for 'offset'
 *   },
 * });
 */
export function useSearchClientsQuery(
  baseOptions: Apollo.QueryHookOptions<
    SearchClientsQuery,
    SearchClientsQueryVariables
  >
) {
  const options = { ...defaultOptions, ...baseOptions };
  return Apollo.useQuery<SearchClientsQuery, SearchClientsQueryVariables>(
    SearchClientsDocument,
    options
  );
}
export function useSearchClientsLazyQuery(
  baseOptions?: Apollo.LazyQueryHookOptions<
    SearchClientsQuery,
    SearchClientsQueryVariables
  >
) {
  const options = { ...defaultOptions, ...baseOptions };
  return Apollo.useLazyQuery<SearchClientsQuery, SearchClientsQueryVariables>(
    SearchClientsDocument,
    options
  );
}
export type SearchClientsQueryHookResult = ReturnType<
  typeof useSearchClientsQuery
>;
export type SearchClientsLazyQueryHookResult = ReturnType<
  typeof useSearchClientsLazyQuery
>;
export type SearchClientsQueryResult = Apollo.QueryResult<
  SearchClientsQuery,
  SearchClientsQueryVariables
>;
export const GetClientDocument = gql`
  query GetClient($id: ID!) {
    client(id: $id) {
      ...ClientFields
    }
  }
  ${ClientFieldsFragmentDoc}
`;

/**
 * __useGetClientQuery__
 *
 * To run a query within a React component, call `useGetClientQuery` and pass it any options that fit your needs.
 * When your component renders, `useGetClientQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useGetClientQuery({
 *   variables: {
 *      id: // value for 'id'
 *   },
 * });
 */
export function useGetClientQuery(
  baseOptions: Apollo.QueryHookOptions<GetClientQuery, GetClientQueryVariables>
) {
  const options = { ...defaultOptions, ...baseOptions };
  return Apollo.useQuery<GetClientQuery, GetClientQueryVariables>(
    GetClientDocument,
    options
  );
}
export function useGetClientLazyQuery(
  baseOptions?: Apollo.LazyQueryHookOptions<
    GetClientQuery,
    GetClientQueryVariables
  >
) {
  const options = { ...defaultOptions, ...baseOptions };
  return Apollo.useLazyQuery<GetClientQuery, GetClientQueryVariables>(
    GetClientDocument,
    options
  );
}
export type GetClientQueryHookResult = ReturnType<typeof useGetClientQuery>;
export type GetClientLazyQueryHookResult = ReturnType<
  typeof useGetClientLazyQuery
>;
export type GetClientQueryResult = Apollo.QueryResult<
  GetClientQuery,
  GetClientQueryVariables
>;
export const GetClientWithEnrollmentsDocument = gql`
  query GetClientWithEnrollments(
    $id: ID!
    $enrollmentsLimit: Int = 10
    $enrollmentsOffset: Int = 0
  ) {
    client(id: $id) {
      ...ClientFields
      enrollments(
        limit: $enrollmentsLimit
        offset: $enrollmentsOffset
        sortOrder: MOST_RECENT
      ) {
        offset
        limit
        nodesCount
        nodes {
          ...EnrollmentFields
        }
      }
    }
  }
  ${ClientFieldsFragmentDoc}
  ${EnrollmentFieldsFragmentDoc}
`;

/**
 * __useGetClientWithEnrollmentsQuery__
 *
 * To run a query within a React component, call `useGetClientWithEnrollmentsQuery` and pass it any options that fit your needs.
 * When your component renders, `useGetClientWithEnrollmentsQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useGetClientWithEnrollmentsQuery({
 *   variables: {
 *      id: // value for 'id'
 *      enrollmentsLimit: // value for 'enrollmentsLimit'
 *      enrollmentsOffset: // value for 'enrollmentsOffset'
 *   },
 * });
 */
export function useGetClientWithEnrollmentsQuery(
  baseOptions: Apollo.QueryHookOptions<
    GetClientWithEnrollmentsQuery,
    GetClientWithEnrollmentsQueryVariables
  >
) {
  const options = { ...defaultOptions, ...baseOptions };
  return Apollo.useQuery<
    GetClientWithEnrollmentsQuery,
    GetClientWithEnrollmentsQueryVariables
  >(GetClientWithEnrollmentsDocument, options);
}
export function useGetClientWithEnrollmentsLazyQuery(
  baseOptions?: Apollo.LazyQueryHookOptions<
    GetClientWithEnrollmentsQuery,
    GetClientWithEnrollmentsQueryVariables
  >
) {
  const options = { ...defaultOptions, ...baseOptions };
  return Apollo.useLazyQuery<
    GetClientWithEnrollmentsQuery,
    GetClientWithEnrollmentsQueryVariables
  >(GetClientWithEnrollmentsDocument, options);
}
export type GetClientWithEnrollmentsQueryHookResult = ReturnType<
  typeof useGetClientWithEnrollmentsQuery
>;
export type GetClientWithEnrollmentsLazyQueryHookResult = ReturnType<
  typeof useGetClientWithEnrollmentsLazyQuery
>;
export type GetClientWithEnrollmentsQueryResult = Apollo.QueryResult<
  GetClientWithEnrollmentsQuery,
  GetClientWithEnrollmentsQueryVariables
>;
export const CreateClientDocument = gql`
  mutation CreateClient($input: CreateClientInput!) {
    createClient(input: $input) {
      clientMutationId
      client {
        ...ClientFields
      }
      errors {
        type
        attribute
        message
        fullMessage
      }
    }
  }
  ${ClientFieldsFragmentDoc}
`;
export type CreateClientMutationFn = Apollo.MutationFunction<
  CreateClientMutation,
  CreateClientMutationVariables
>;

/**
 * __useCreateClientMutation__
 *
 * To run a mutation, you first call `useCreateClientMutation` within a React component and pass it any options that fit your needs.
 * When your component renders, `useCreateClientMutation` returns a tuple that includes:
 * - A mutate function that you can call at any time to execute the mutation
 * - An object with fields that represent the current status of the mutation's execution
 *
 * @param baseOptions options that will be passed into the mutation, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options-2;
 *
 * @example
 * const [createClientMutation, { data, loading, error }] = useCreateClientMutation({
 *   variables: {
 *      input: // value for 'input'
 *   },
 * });
 */
export function useCreateClientMutation(
  baseOptions?: Apollo.MutationHookOptions<
    CreateClientMutation,
    CreateClientMutationVariables
  >
) {
  const options = { ...defaultOptions, ...baseOptions };
  return Apollo.useMutation<
    CreateClientMutation,
    CreateClientMutationVariables
  >(CreateClientDocument, options);
}
export type CreateClientMutationHookResult = ReturnType<
  typeof useCreateClientMutation
>;
export type CreateClientMutationResult =
  Apollo.MutationResult<CreateClientMutation>;
export type CreateClientMutationOptions = Apollo.BaseMutationOptions<
  CreateClientMutation,
  CreateClientMutationVariables
>;
export const GetProjectsForSelectDocument = gql`
  query GetProjectsForSelect {
    projects(sortOrder: ORGANIZATION_AND_NAME) {
      ...ProjectFields
      organization {
        organizationName
      }
    }
  }
  ${ProjectFieldsFragmentDoc}
`;

/**
 * __useGetProjectsForSelectQuery__
 *
 * To run a query within a React component, call `useGetProjectsForSelectQuery` and pass it any options that fit your needs.
 * When your component renders, `useGetProjectsForSelectQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useGetProjectsForSelectQuery({
 *   variables: {
 *   },
 * });
 */
export function useGetProjectsForSelectQuery(
  baseOptions?: Apollo.QueryHookOptions<
    GetProjectsForSelectQuery,
    GetProjectsForSelectQueryVariables
  >
) {
  const options = { ...defaultOptions, ...baseOptions };
  return Apollo.useQuery<
    GetProjectsForSelectQuery,
    GetProjectsForSelectQueryVariables
  >(GetProjectsForSelectDocument, options);
}
export function useGetProjectsForSelectLazyQuery(
  baseOptions?: Apollo.LazyQueryHookOptions<
    GetProjectsForSelectQuery,
    GetProjectsForSelectQueryVariables
  >
) {
  const options = { ...defaultOptions, ...baseOptions };
  return Apollo.useLazyQuery<
    GetProjectsForSelectQuery,
    GetProjectsForSelectQueryVariables
  >(GetProjectsForSelectDocument, options);
}
export type GetProjectsForSelectQueryHookResult = ReturnType<
  typeof useGetProjectsForSelectQuery
>;
export type GetProjectsForSelectLazyQueryHookResult = ReturnType<
  typeof useGetProjectsForSelectLazyQuery
>;
export type GetProjectsForSelectQueryResult = Apollo.QueryResult<
  GetProjectsForSelectQuery,
  GetProjectsForSelectQueryVariables
>;
export const GetOrganizationsForSelectDocument = gql`
  query GetOrganizationsForSelect {
    organizations(sortOrder: NAME) {
      ...OrganizationFields
    }
  }
  ${OrganizationFieldsFragmentDoc}
`;

/**
 * __useGetOrganizationsForSelectQuery__
 *
 * To run a query within a React component, call `useGetOrganizationsForSelectQuery` and pass it any options that fit your needs.
 * When your component renders, `useGetOrganizationsForSelectQuery` returns an object from Apollo Client that contains loading, error, and data properties
 * you can use to render your UI.
 *
 * @param baseOptions options that will be passed into the query, supported options are listed on: https://www.apollographql.com/docs/react/api/react-hooks/#options;
 *
 * @example
 * const { data, loading, error } = useGetOrganizationsForSelectQuery({
 *   variables: {
 *   },
 * });
 */
export function useGetOrganizationsForSelectQuery(
  baseOptions?: Apollo.QueryHookOptions<
    GetOrganizationsForSelectQuery,
    GetOrganizationsForSelectQueryVariables
  >
) {
  const options = { ...defaultOptions, ...baseOptions };
  return Apollo.useQuery<
    GetOrganizationsForSelectQuery,
    GetOrganizationsForSelectQueryVariables
  >(GetOrganizationsForSelectDocument, options);
}
export function useGetOrganizationsForSelectLazyQuery(
  baseOptions?: Apollo.LazyQueryHookOptions<
    GetOrganizationsForSelectQuery,
    GetOrganizationsForSelectQueryVariables
  >
) {
  const options = { ...defaultOptions, ...baseOptions };
  return Apollo.useLazyQuery<
    GetOrganizationsForSelectQuery,
    GetOrganizationsForSelectQueryVariables
  >(GetOrganizationsForSelectDocument, options);
}
export type GetOrganizationsForSelectQueryHookResult = ReturnType<
  typeof useGetOrganizationsForSelectQuery
>;
export type GetOrganizationsForSelectLazyQueryHookResult = ReturnType<
  typeof useGetOrganizationsForSelectLazyQuery
>;
export type GetOrganizationsForSelectQueryResult = Apollo.QueryResult<
  GetOrganizationsForSelectQuery,
  GetOrganizationsForSelectQueryVariables
>;
