name: Build and test app

on:
  push:
    branches: [ stable ]
  pull_request:
    branches: [ stable ]

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version-file: '.nvmrc'

    - name: Install dependencies
      run: |
        corepack enable
        yarn install --offline

    # - name: Audit dependencies
    #   run: |
    #     yarn audit --groups dependencies

    - name: Lint and Format
      run: |
        yarn tsc
        yarn format:check
        yarn lint:check

    - name: Test
      run: |
        yarn test

    - name: Storybook smoke test
      run: |
        yarn storybook --smoke-test

    - name: Start mock server
      run: |
        cd serverMock
        yarn install
        yarn start &
        sleep 5

    - name: Run Cypress tests
      timeout-minutes: 5
      uses: cypress-io/github-action@v5.0.0
      env:
        HMIS_SERVER_URL: 'http://localhost:4000'
        HMIS_HOST: 'localhost'
        CYPRESS_BASE_URL: 'https://127.0.0.1:5173/'
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        install: false
        build: yarn build
        start: DEBUG=vite:plugin:mkcert yarn preview
        browser: chrome
        spec: |
          cypress/e2e/mocked/*.cy.ts
