name: Build and test app

on:
  push:
    branches: [ stable ]
  pull_request:
    branches: [ stable ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version-file: '.nvmrc'

    - name: Install dependencies
      run: |
        corepack enable
        yarn install --offline

    - name: Audit dependencies
      run: |
        yarn audit --groups dependencies

    - name: Lint and Format
      run: |
        yarn format:check
        yarn lint:check

    - name: Test
      run: |
        yarn test

    - name: Storybook smoke test
      run: |
        yarn storybook --smoke-test

    - name: Build
      run: |
        yarn build
